import { http, HttpResponse } from 'msw'

const getPosts = http.get('/api/v1/posts', () => {
  return HttpResponse.json(posts,
    { status: 200 })
})

export default [getPosts]

const posts = [
  {
    id: 1,
    title: 'Hice un portafolio y te lo muestro',
    category: 'Portafolios',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-02-11T05:00:00.000Z',
    updated_at: null,
    vote_count: -4,
    comment_count: 4,
    vote_direction: 1,
    author_id: 1,
    body: 'laudantium enim quasi est quidem magnam voluptate ipsam eos\ntempora quo necessitatibus\ndolor quam autem quasi\nreiciendis et nam sapiente accusantium'
  },
  {
    id: 2,
    title: 'lo que sea ',
    category: 'Proyectos grupales',
    parent_id: 1,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-03-19T05:00:00.000Z',
    updated_at: null,
    vote_count: -10,
    comment_count: 4,
    vote_direction: 0,
    author_id: 2,
    body: 'est natus enim nihil est dolore omnis voluptatem numquam\net omnis occaecati quod ullam at\nvoluptatem error expedita pariatur\nnihil sint nostrum voluptatem reiciendis et'
  },
  {
    id: 3,
    title: 'lo que sea 1',
    category: 'Hojas de vida',
    parent_id: 1,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    created_at: '2023-07-21T05:00:00.000Z',
    updated_at: null,
    vote_count: -9,
    comment_count: 5,
    vote_direction: 0,
    author_id: 3,
    body: 'quia molestiae reprehenderit quasi aspernatur\naut expedita occaecati aliquam eveniet laudantium\nomnis quibusdam delectus saepe quia accusamus maiores nam est\ncum et ducimus et vero voluptates excepturi deleniti ratione'
  },
  {
    id: 4,
    title: 'lo que sea 2',
    category: 'Ofertas de trabajo',
    parent_id: 1,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-03-21T05:00:00.000Z',
    updated_at: null,
    vote_count: 6,
    comment_count: 3,
    vote_direction: -1,
    author_id: 1,
    body: 'non et atque\noccaecati deserunt quas accusantium unde odit nobis qui voluptatem\nquia voluptas consequuntur itaque dolor\net qui rerum deleniti ut occaecati'
  },
  {
    id: 5,
    title: 'lo que sea 3',
    category: 'Sugerencias de cursos',
    parent_id: 1,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    created_at: '2023-08-13T05:00:00.000Z',
    updated_at: null,
    vote_count: 1,
    comment_count: 0,
    vote_direction: 1,
    author_id: 3,
    body: 'harum non quasi et ratione\ntempore iure ex voluptates in ratione\nharum architecto fugit inventore cupiditate\nvoluptates magni quo et'
  },
  {
    id: 7,
    title: 'lo que sea 4',
    category: 'Ofertas de trabajo',
    parent_id: 2,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-11-24T05:00:00.000Z',
    updated_at: null,
    vote_count: 6,
    comment_count: 0,
    vote_direction: -1,
    author_id: 1,
    body: 'maiores sed dolores similique labore et inventore et\nquasi temporibus esse sunt id et\neos voluptatem aliquam\naliquid ratione corporis molestiae mollitia quia et magnam dolor'
  },
  {
    id: 8,
    title: 'lo que sea 5',
    category: 'Portafolios',
    parent_id: 2,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-07-20T05:00:00.000Z',
    updated_at: null,
    vote_count: -7,
    comment_count: 0,
    vote_direction: 0,
    author_id: 2,
    body: 'ut voluptatem corrupti velit\nad voluptatem maiores\net nisi velit vero accusamus maiores\nvoluptates quia aliquid ullam eaque'
  },
  {
    id: 9,
    title: 'lo que sea 6',
    category: 'Proyectos grupales',
    parent_id: 2,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-03-18T05:00:00.000Z',
    updated_at: null,
    vote_count: -2,
    comment_count: 0,
    vote_direction: 1,
    author_id: 2,
    body: 'sapiente assumenda molestiae atque\nadipisci laborum distinctio aperiam et ab ut omnis\net occaecati aspernatur odit sit rem expedita\nquas enim ipsam minus'
  },
  {
    id: 10,
    title: 'lo que sea 7',
    category: 'Hojas de vida',
    parent_id: 2,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-02-01T05:00:00.000Z',
    updated_at: null,
    vote_count: -6,
    comment_count: 0,
    vote_direction: 0,
    author_id: 2,
    body: 'voluptate iusto quis nobis reprehenderit ipsum amet nulla\nquia quas dolores velit et non\naut quia necessitatibus\nnostrum quaerat nulla et accusamus nisi facilis'
  },
  {
    id: 11,
    title: 'lo que sea 8',
    category: 'Sugerencias de cursos',
    parent_id: 3,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-06-14T05:00:00.000Z',
    updated_at: null,
    vote_count: 0,
    comment_count: 0,
    vote_direction: 0,
    author_id: 1,
    body: 'ut dolorum nostrum id quia aut est\nfuga est inventore vel eligendi explicabo quis consectetur\naut occaecati repellat id natus quo est\nut blanditiis quia ut vel ut maiores ea'
  },
  {
    id: 12,
    title: 'lo que sea 9',
    category: 'Portafolios',
    parent_id: 3,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-11-20T05:00:00.000Z',
    updated_at: null,
    vote_count: 2,
    comment_count: 0,
    vote_direction: 0,
    author_id: 2,
    body: 'expedita maiores dignissimos facilis\nipsum est rem est fugit velit sequi\neum odio dolores dolor totam\noccaecati ratione eius rem velit'
  },
  {
    id: 13,
    title: 'lo que sea 10',
    category: 'Ofertas de trabajo',
    parent_id: 3,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    created_at: '2023-02-08T05:00:00.000Z',
    updated_at: null,
    vote_count: -10,
    comment_count: 0,
    vote_direction: 1,
    author_id: 3,
    body: 'fuga eos qui dolor rerum\ninventore corporis exercitationem\ncorporis cupiditate et deserunt recusandae est sed quis culpa\neum maiores corporis et'
  },
  {
    id: 14,
    title: 'lo que sea 11',
    category: 'Hojas de vida',
    parent_id: 3,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    created_at: '2023-06-24T05:00:00.000Z',
    updated_at: null,
    vote_count: 4,
    comment_count: 0,
    vote_direction: 0,
    author_id: 3,
    body: 'vel quae voluptas qui exercitationem\nvoluptatibus unde sed\nminima et qui ipsam aspernatur\nexpedita magnam laudantium et et quaerat ut qui dolorum'
  },
  {
    id: 15,
    title: 'lo que sea 12',
    category: 'Ofertas de trabajo',
    parent_id: 3,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    created_at: '2023-11-21T05:00:00.000Z',
    updated_at: null,
    vote_count: -2,
    comment_count: 0,
    vote_direction: 0,
    author_id: 3,
    body: 'nihil ut voluptates blanditiis autem odio dicta rerum\nquisquam saepe et est\nsunt quasi nemo laudantium deserunt\nmolestias tempora quo quia'
  },
  {
    id: 16,
    title: 'lo que sea 13',
    category: 'Sugerencias de cursos',
    parent_id: 4,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-07-10T05:00:00.000Z',
    updated_at: null,
    vote_count: 0,
    comment_count: 0,
    vote_direction: 0,
    author_id: 1,
    body: 'iste ut laborum aliquid velit facere itaque\nquo ut soluta dicta voluptate\nerror tempore aut et\nsequi reiciendis dignissimos expedita consequuntur libero sed fugiat facilis'
  },
  {
    id: 17,
    title: 'lo que sea 14',
    category: 'Portafolios',
    parent_id: 4,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    created_at: '2023-02-17T05:00:00.000Z',
    updated_at: null,
    vote_count: 3,
    comment_count: 0,
    vote_direction: 1,
    author_id: 2,
    body: 'consequatur necessitatibus totam sed sit dolorum\nrecusandae quae odio excepturi voluptatum harum voluptas\nquisquam sit ad eveniet delectus\ndoloribus odio qui non labore'
  },
  {
    id: 18,
    title: 'lo que sea 15',
    category: 'Ofertas de trabajo',
    parent_id: 4,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Eliseo',
    created_at: '2023-02-21T05:00:00.000Z',
    updated_at: null,
    vote_count: 7,
    comment_count: 0,
    vote_direction: -1,
    author_id: 1,
    body: 'veritatis voluptates necessitatibus maiores corrupti\nneque et exercitationem amet sit et\nullam velit sit magnam laborum\nmagni ut molestias'
  },
  {
    id: 21,
    title: 'lo que sea 16',
    category: 'Hojas de vida',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    author_id: 2,
    created_at: '2023-02-03T05:00:00.000Z',
    updated_at: null,
    vote_count: 0,
    comment_count: 0,
    vote_direction: 0,
    body: 'deleniti aut sed molestias explicabo\ncommodi odio ratione nesciunt\nvoluptate doloremque est\nnam autem error delectus'
  },
  {
    id: 22,
    title: 'lo que sea 17',
    category: 'Proyectos grupales',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    author_id: 2,
    created_at: '2023-06-20T05:00:00.000Z',
    updated_at: null,
    vote_count: -8,
    comment_count: 0,
    vote_direction: 0,
    body: 'qui ipsa animi nostrum praesentium voluptatibus odit\nqui non impedit cum qui nostrum aliquid fuga explicabo\nvoluptatem fugit earum voluptas exercitationem temporibus dignissimos distinctio\nesse inventore reprehenderit quidem ut incidunt nihil necessitatibus rerum'
  },
  {
    id: 23,
    title: 'lo que sea 18',
    category: 'Ofertas de trabajo',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    author_id: 3,
    created_at: '2023-05-10T05:00:00.000Z',
    updated_at: null,
    vote_count: -2,
    comment_count: 0,
    vote_direction: 0,
    body: 'voluptates provident repellendus iusto perspiciatis ex fugiat ut\nut dolor nam aliquid et expedita voluptate\nsunt vitae illo rerum in quos\nvel eligendi enim quae fugiat est'
  },
  {
    id: 24,
    title: 'lo que sea 19',
    category: 'Hojas de vida',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Nikita',
    author_id: 3,
    created_at: '2023-05-21T05:00:00.000Z',
    updated_at: null,
    vote_count: 8,
    comment_count: 0,
    vote_direction: 0,
    body: 'repudiandae repellat quia\nsequi est dolore explicabo nihil et\net sit et\net praesentium iste atque asperiores tenetur'
  },
  {
    id: 25,
    title: 'lo que sea 20',
    category: 'Portafolios',
    parent_id: null,
    avatar: 'https://southernplasticsurgery.com.au/wp-content/uploads/2013/10/user-placeholder.png',
    username: 'Jayne_Kuhic',
    author_id: 2,
    created_at: '2023-06-20T05:00:00.000Z',
    updated_at: null,
    vote_count: -5,
    comment_count: 0,
    vote_direction: 1,
    body: 'sunt aut quae laboriosam sit ut impedit\nadipisci harum laborum totam deleniti voluptas odit rem ea\nnon iure distinctio ut velit doloribus\net non ex'
  }
]
